version: 2.1

executors:
  common-image:
    docker:
      - image: cimg/python:3.10.5-node


commands:
  install-all-the-things:
    description: Run common installation commands
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install aws cli
          command: sudo apt-get update && sudo apt-get -y -qq install awscli && aws --version
      - run:
          name: Install Deps
          command: yarn install
      - run:
          name: Install pipenv
          command: python3 -m pip install --upgrade pip && python3 -m pip install pipenv && pipenv install

jobs:
  test:
    executor:
      name: common-image
    steps:
      - install-all-the-things: {}
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run:
          name: Yarn Build
          command: yarn build
  deployStaging:
    executor:
      name: common-image
    steps:
      - install-all-the-things: {}
      - run:
          name: Build site
          command: yarn build
      - run:
          name: Yarn Deploy Staging
          command: aws s3 sync build/ s3://staging-semgrep-dev/docs
  deployProd:
    executor:
      name: common-image
    steps:
      - install-all-the-things: {}
      - run:
          name: Build site
          command: yarn build
      - run:
          name: Yarn Prod Deploy
          command: aws s3 sync build/ s3://semgrep-docs/docs

workflows:
  build-and-deploy:
    jobs:
      - test
      - deployStaging:
          context:
            - aws
          requires:
            - test
          filters:
            branches:
              only:
                - develop
      - deployProd:
          context:
            - aws
          requires:
            - test
          filters:
            branches:
              only:
                - main
